### ISSUE TITLE
building pet with llvm/clang versions >= 4

### ISSUE THREAD

**Issue by ajaypanyala** [Meinersbur/pet#2]
Hi,

I am trying to build the latest development version of libpet and see the following build error when using clang 4.0

```
extract_interface.cc: In function ‘int main(int, char**)’:
extract_interface.cc:383:34: error: no matching function for call to ‘clang::CompilerInstance::setInvocation(clang::CompilerInvocation*&)’
   Clang->setInvocation(invocation);
```

I was able to build pet by tweaking that line in isl/interface/extract_interface.cc and pet.cc as shown in the diffs shown below:

https://paste.ee/p/8jFWe
https://paste.ee/p/caoEM

Similarly, when using Clang v5:

https://paste.ee/p/fpYKq

I realize doing this breaks compatibility with older versions of Clang. Please suggest a cleaner fix that enables using the latest versions of Clang.

Thanks!

**Comment by Meinersbur** [comment]
Hi,

are you using pet from this repository or the upstream one? Upstream should
work with clang 4.0. I didn't update this repository for some time now.

The usual strategy for supporting multiple versions is to grep the clang
header for which arguments a method accepts in configure.ac, have a #define
in config.h for it and #ifdef the code for each variant in the pet source.

Michael

**Comment by ajaypanyala** [comment]
Thanks! The upstream repo works fine with clang 4&5.
